# Generated by Django 2.1.2 on 2019-04-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='Department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Departments'),
        ),
        migrations.AddField(
            model_name='marks',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Course'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.exam'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Subjects'),
        ),
    ]
