# Generated by Django 2.1.2 on 2019-04-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_auto_20190414_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('Department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Departments')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Course')),
                ('exam', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.exam')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='center.Subjects')),
            ],
        ),
    ]
