# Generated by Django 2.1.2 on 2019-04-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='exam',
            new_name='exams',
        ),
    ]
