# Generated by Django 2.1.2 on 2019-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_auto_20190414_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='exams',
            field=models.CharField(default='', max_length=200),
        ),
    ]
