# Generated by Django 2.1.2 on 2019-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_auto_20190414_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='course',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
