# Generated by Django 2.1.2 on 2019-04-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0017_auto_20190414_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Departments')),
                ('ExamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.exam')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Subjects')),
            ],
        ),
    ]
